### ISSUE TITLE
Can't locate loadable object for module Digest::MD5

### ISSUE THREAD

**Issue by matiasirazoqui** [gjospin/PhyloSift#479]
Hi,
Today I tried to run phylosift, but it keeps giving me the error I paste down here. I've installed the MD5 module via CPAN, so the module is there. I've also tried copying the library in the folders where the perl modules are. Theoretically, Phylosift searches for MD5 and, if it doesn't find it, uses a legacy version that comes within the package, but it keeps telling me it can't locate the MD5 module. I'm working on a CentOS 7.2.1511 server, with Perl 5.16 installed.

[matias@localhost Phylosift]$ ./phylosift dbupdate
Can't locate loadable object for module Digest::MD5 in @INC (@INC contains: /home/matias/Phylosift/bin/../lib /home/matias/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /home/matias/perl5/lib/perl5/5.16.3 /home/matias/perl5/lib/perl5/x86_64-linux-thread-multi /home/matias/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/matias/Phylosift/bin/../lib/Phylosift/FastSearch.pm line 25.
Compilation failed in require at /home/matias/Phylosift/bin/../lib/Phylosift/FastSearch.pm line 25.
BEGIN failed--compilation aborted at /home/matias/Phylosift/bin/../lib/Phylosift/FastSearch.pm line 25.
Compilation failed in require at /home/matias/Phylosift/bin/../lib/Phylosift/Phylosift.pm line 18.
BEGIN failed--compilation aborted at /home/matias/Phylosift/bin/../lib/Phylosift/Phylosift.pm line 18.
Compilation failed in require at /home/matias/Phylosift/bin/../lib/Phylosift/Command/test_lineage.pm line 4.
BEGIN failed--compilation aborted at /home/matias/Phylosift/bin/../lib/Phylosift/Command/test_lineage.pm line 4.
Compilation failed in require at /home/matias/Phylosift/bin/../lib/App/Cmd.pm line 84.
        App::Cmd::_command('Phylosift', undef) called at /home/matias/Phylosift/bin/../lib/App/Cmd.pm line 59
        App::Cmd::new('Phylosift') called at /home/matias/Phylosift/bin/../lib/App/Cmd.pm line 164
        App::Cmd::run('Phylosift') called at /home/matias/Phylosift/bin/phylosift line 7
